package dev.rotalex.lutter.serialization

import dev.rotalex.lutter.model.doc.AppSpec
import dev.rotalex.lutter.model.doc.DocumentMeta
import dev.rotalex.lutter.model.doc.ModifierEntry
import dev.rotalex.lutter.model.doc.Node
import dev.rotalex.lutter.model.doc.NodeTable
import dev.rotalex.lutter.model.doc.Page
import dev.rotalex.lutter.model.doc.UiDocument
import dev.rotalex.lutter.model.expr.PropertyValue
import dev.rotalex.lutter.model.ids.ComponentType
import dev.rotalex.lutter.model.ids.ModifierType
import dev.rotalex.lutter.model.ids.NodeId
import dev.rotalex.lutter.model.ids.PageId
import dev.rotalex.lutter.model.ids.PropertyKey
import dev.rotalex.lutter.model.ids.SlotName
import dev.rotalex.lutter.model.value.Value
import dev.rotalex.lutter.testsupport.Golden
import dev.rotalex.lutter.testsupport.classpathGoldenSource
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * PLAN §32 Phase 3's acceptance, made real: **golden JSON files identical on every target.**
 *
 * The words that matter are "identical on every target", and they are what the committed file
 * is for. `CanonicalJsonWriterTest` pins the writer's *rules* against inputs it parses in the
 * same run; this pins the writer's *output* against bytes somebody committed and a reviewer
 * read. The difference matters because the two fail differently: a rule can be implemented
 * correctly and still produce bytes no one agreed to, and only a committed file notices.
 *
 * ### Why the golden is readable on purpose
 *
 * Every line of `goldens/counter-document.golden` is evidence of a §18.2 rule, and the file is
 * shaped so a reviewer can check it without running anything:
 *
 *  * **Envelope keys are sorted, not declared in `Envelope`'s order.** `format`,
 *    `formatVersion`, `payload`, `schemaVersion` is UTF-16 lexicographic, and `payload` is
 *    declared third in `Envelope` for the same reason it is written third: `f < p < s`.
 *  * **Every object is sorted at every depth** — `app` before `components` before `meta`
 *    before `nodes` before `pages`, and `id` before `modifiers` before `props` before
 *    `slots` before `type`.
 *  * **The document was built in the opposite order.** `props` is declared width, spacing,
 *    padding and the golden reads padding, spacing, width; the two nodes are added total
 *    before root and the golden reads `n_root` before `n_total`. If the writer ever stopped
 *    sorting, this file would change without a line of it being edited.
 *  * **`modifiers` keeps model order, because it is an array.** `layout.padding` is declared
 *    before `layout.background` and the golden preserves that, which is the visible proof of
 *    the asymmetry `Node.modifiers` documents: sorting a map is a canonicalization, sorting a
 *    modifier chain would be a semantic change.
 *  * **Numbers are canonical and never `toString()`.** `Dp(0.1f)` is the interesting one: the
 *    stored `Float` widens to `0.10000000149011612`, and the golden says `0.1`. `16.5` widens
 *    to an exact half, and `320` has no fractional part at all and so carries no decimal
 *    point. Three spellings, one of which a `Double.toString()` would get wrong.
 *
 * ### How the golden was written
 *
 * By hand, from the source, and then reviewed — not from a run. A golden generated by the
 * same build that asserts it is a tautology: it would agree with any writer, including a
 * broken one. `Golden.assertEquals(..., update = true)` returns the text to persist, which is
 * how the file is regenerated, and every regeneration is a diff a reviewer reads.
 *
 * ### The two property checks
 *
 * The exact-bytes assertion is the one that guards the format. The two below guard the
 * *file*, independently of the codec, by parsing the committed bytes and checking the rules
 * against them directly. They exist because an unreadable golden fails silently: if a
 * regeneration once wrote an unsorted file, the byte assertion would keep passing on every
 * subsequent run and nothing would notice that the expectation had stopped meaning anything.
 */
class CanonicalJsonGoldenTest {

    private val document = UiDocument(
        meta = DocumentMeta("Counter"),
        app = AppSpec(packageName = "com.example.counter", startPage = PageId("p_home")),
        pages = mapOf(
            PageId("p_home") to Page(
                id = PageId("p_home"),
                name = "HomeScreen",
                route = "/home",
                root = NodeId("n_root"),
            ),
        ),
        components = emptyMap(),
        nodes = NodeTable.EMPTY
            .with(
                Node(
                    id = NodeId("n_total"),
                    type = ComponentType("m3.Text"),
                    props = mapOf(
                        PropertyKey("text") to PropertyValue.Const(Value.Str("Total")),
                    ),
                ),
            )
            .with(
                Node(
                    id = NodeId("n_root"),
                    type = ComponentType("core.Column"),
                    // Declared in the reverse of the order §18.2 writes them.
                    props = mapOf(
                        PropertyKey("width") to PropertyValue.Const(Value.Dp(320f)),
                        PropertyKey("spacing") to PropertyValue.Const(Value.Dp(0.1f)),
                        PropertyKey("padding") to PropertyValue.Const(Value.Dp(16.5f)),
                    ),
                    // An array, so the order is the document's and the writer keeps it.
                    modifiers = listOf(
                        ModifierEntry(
                            type = ModifierType("layout.padding"),
                            args = mapOf(PropertyKey("all") to PropertyValue.Const(Value.Dp(16f))),
                        ),
                        ModifierEntry(type = ModifierType("layout.background")),
                    ),
                    slots = mapOf(SlotName("children") to listOf(NodeId("n_total"))),
                ),
            ),
    )

    private fun goldenText(): String = Golden.read(GOLDEN, classpathGoldenSource())

    @Test
    fun `the canonical envelope of a document is the committed golden`() {
        Golden.assertEquals(GOLDEN, JsonDocumentCodec.encode(document).decodeToString(), classpathGoldenSource())
    }

    @Test
    fun `the golden's own object keys are sorted at every depth`() {
        val unsorted = unsortedObjects(ForgeJson.parseToJsonElement(goldenText()), "$")

        assertEquals(emptyList<String>(), unsorted, unsorted.joinToString("\n"))
    }

    @Test
    fun `the golden's own numbers are canonical, with no widened float and no exponent`() {
        val nonCanonical = nonCanonicalNumbers(ForgeJson.parseToJsonElement(goldenText()), "$")

        assertEquals(emptyList<String>(), nonCanonical, nonCanonical.joinToString("\n"))
    }

    /** Every object in the file whose keys are not in UTF-16 order, named by its path. */
    private fun unsortedObjects(element: JsonElement, path: String): List<String> {
        val violations = mutableListOf<String>()
        when (element) {
            is JsonObject -> {
                val keys = element.keys.toList()
                val expected = keys.sorted()
                if (keys != expected) violations += "$path: keys are $keys, not $expected"
                element.forEach { (key, value) -> violations += unsortedObjects(value, "$path.$key") }
            }

            is JsonArray -> element.forEachIndexed { index, value ->
                violations += unsortedObjects(value, "$path[$index]")
            }

            is JsonPrimitive -> Unit
        }
        return violations
    }

    /**
     * Every number in the file that D1's formatter could not have written.
     *
     * A canonical number is a plain decimal with at most four fractional digits, so this is the
     * check that turns a widened `Float` into a failure rather than a longer number: `0.1f`
     * widens to `0.10000000149011612`, and `toString()` on it would keep all of them.
     */
    private fun nonCanonicalNumbers(element: JsonElement, path: String): List<String> {
        val violations = mutableListOf<String>()
        when (element) {
            is JsonObject -> element.forEach { (key, value) ->
                violations += nonCanonicalNumbers(value, "$path.$key")
            }

            is JsonArray -> element.forEachIndexed { index, value ->
                violations += nonCanonicalNumbers(value, "$path[$index]")
            }

            // `JsonNull` is a `JsonPrimitive` that is not a number, and `explicitNulls = false`
            // means it is not a thing this module writes often enough to police.
            is JsonPrimitive ->
                if (element !is JsonNull && !element.isString && !CANONICAL_NUMBER.matches(element.content)) {
                    violations += "$path: '$element' is not a canonical number"
                }
        }
        return violations
    }

    private companion object {
        const val GOLDEN = "goldens/counter-document.golden"

        /** `-?\d+(\.\d{1,4})?`: at most four fractional digits, never an exponent. */
        val CANONICAL_NUMBER = Regex("""-?\d+(\.\d{1,4})?""")
    }
}