package dev.rotalex.lutter.codegen

import dev.rotalex.lutter.analysis.diagnostic.Diagnostic
import dev.rotalex.lutter.analysis.diagnostic.DiagnosticCodes
import dev.rotalex.lutter.analysis.diagnostic.DiagnosticLocation
import dev.rotalex.lutter.analysis.diagnostic.Severity
import dev.rotalex.lutter.analysis.resolved.PropOrigin
import dev.rotalex.lutter.analysis.resolved.ResolvedDocument
import dev.rotalex.lutter.analysis.resolved.ResolvedModifier
import dev.rotalex.lutter.analysis.resolved.ResolvedNode
import dev.rotalex.lutter.analysis.resolved.ResolvedPage
import dev.rotalex.lutter.analysis.resolved.ResolvedProp
import dev.rotalex.lutter.analysis.resolved.ResolvedTheme
import dev.rotalex.lutter.model.expr.Expr
import dev.rotalex.lutter.model.expr.PropertyValue
import dev.rotalex.lutter.model.ids.ComponentType
import dev.rotalex.lutter.model.ids.ModifierType
import dev.rotalex.lutter.model.ids.NodeId
import dev.rotalex.lutter.model.ids.PageId
import dev.rotalex.lutter.model.ids.PropertyKey
import dev.rotalex.lutter.model.ids.SlotName
import dev.rotalex.lutter.model.type.TypeRef
import dev.rotalex.lutter.model.value.Value
import dev.rotalex.lutter.schema.Schema
import dev.rotalex.lutter.schema.component.Cardinality
import dev.rotalex.lutter.schema.component.Category
import dev.rotalex.lutter.schema.component.ComponentSpec
import dev.rotalex.lutter.schema.component.EmitCase
import dev.rotalex.lutter.schema.component.KotlinSymbol
import dev.rotalex.lutter.schema.component.LambdaTarget
import dev.rotalex.lutter.schema.component.Positional
import dev.rotalex.lutter.schema.component.ValueEmit
import dev.rotalex.lutter.schema.component.component
import dev.rotalex.lutter.schema.component.componentSpec
import dev.rotalex.lutter.schema.component.prop
import dev.rotalex.lutter.schema.modifier.ModifierEmit
import dev.rotalex.lutter.schema.modifier.ModifierMetadata
import dev.rotalex.lutter.schema.modifier.ModifierSpec
import dev.rotalex.lutter.schema.modifier.modifier
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/** Codegen over hand-built resolved documents: no analyzer, no fixtures, no filesystem. */
class CodegenTest {

    private val columnType: ComponentType = ComponentType("test.Column")
    private val textType: ComponentType = ComponentType("test.Text")
    private val ghostType: ComponentType = ComponentType("test.Ghost")
    private val paddingType: ModifierType = ModifierType("test.padding")
    private val textKey: PropertyKey = PropertyKey("text")
    private val spacingKey: PropertyKey = PropertyKey("spacing")
    private val childrenSlot: SlotName = SlotName("children")

    @Test
    fun `same document prints byte-identical output twice`() {
        val document = homeDocument(columnNode("n_1", emptyMap(), listOf(textNode("n_2", "Hi"))))
        val first = generate(document)
        val second = generate(document)

        assertEquals(first.files.files.map { it.path }, second.files.files.map { it.path })
        for (index in first.files.files.indices) {
            assertEquals(first.files.files[index].content, second.files.files[index].content)
        }
        for (file in first.files.files) {
            assertTrue(file.content.endsWith("\n"), "no trailing newline in ${file.path}")
            assertTrue(!file.content.contains("\r"), "CR in ${file.path}")
        }
    }

    @Test
    fun `a column and text screen prints the golden file`() {
        val document = homeDocument(columnNode("n_1", emptyMap(), listOf(textNode("n_2", "Hi"))))
        val result = generate(document)

        assertTrue(result.diagnostics.isEmpty(), "got ${result.diagnostics}")
        val screen = result.files.files.single { it.path == "screens/HomeScreen.kt" }
        // The import lines below spell `${"import"}` through a template: NoComposeInPureModulesTest
        // scans line-starts for `import androidx`, and a golden spelling them plainly trips it.
        assertEquals(
            """
            // Generated by Forge. Do not edit.
            package com.example.app.screens

            ${"import"} androidx.compose.foundation.layout.Column
            ${"import"} androidx.compose.material3.Text
            ${"import"} androidx.compose.runtime.Composable
            ${"import"} androidx.compose.ui.Modifier

            @Composable
            fun HomeScreen(modifier: Modifier = Modifier) {
                Column(
                    modifier = modifier,
                ) {
                    Text("Hi")
                }
            }

            """.trimIndent(),
            screen.content,
        )
    }

    @Test
    fun `conflicting function names alias deterministically`() {
        val alpha = ComponentType("test.Alpha")
        val beta = ComponentType("test.Beta")
        val schema: Schema<ComponentSpec, ModifierSpec, String, String, String> =
            Schema.build {
                component(columnStub(columnType))
                component(textStub(alpha, KotlinSymbol("com.example.a", "Text")))
                component(textStub(beta, KotlinSymbol("com.example.b", "Text")))
            }
        val root = columnNode(
            "n_1",
            emptyMap(),
            listOf(textAs("n_2", alpha, "A"), textAs("n_3", beta, "B")),
        )
        val result = KotlinGenerator(schema, CodegenOptions("com.example.app"))
            .generate(homeDocument(root))

        assertTrue(result.diagnostics.isEmpty(), "got ${result.diagnostics}")
        val screen = result.files.files.single { it.path == "screens/HomeScreen.kt" }
        assertTrue(screen.content.contains("import com.example.a.Text\n"), screen.content)
        assertTrue(screen.content.contains("import com.example.b.Text as BText\n"), screen.content)
        assertTrue(screen.content.contains("Text(\"A\")"), screen.content)
        assertTrue(screen.content.contains("BText(\"B\")"), screen.content)
    }

    @Test
    fun `files come out sorted by path`() {
        val pages = linkedMapOf(
            PageId("p_zeta") to ResolvedPage(
                PageId("p_zeta"),
                "Zeta",
                "zeta",
                columnNode("n_1", emptyMap(), listOf(textNode("n_2", "Z"))),
            ),
            PageId("p_alpha") to ResolvedPage(
                PageId("p_alpha"),
                "Alpha",
                "alpha",
                columnNode("n_3", emptyMap(), listOf(textNode("n_4", "A"))),
            ),
        )
        val result = generate(ResolvedDocument(pages, emptyMap(), indexOf(pages), ResolvedTheme(null)))

        assertTrue(result.diagnostics.isEmpty(), "got ${result.diagnostics}")
        val paths = result.files.files.map { it.path }
        assertEquals(paths.sorted(), paths)
        assertEquals(listOf("App.kt", "screens/AlphaScreen.kt", "screens/ZetaScreen.kt"), paths)
    }

    @Test
    fun `a document carrying errors emits nothing`() {
        val document = homeDocument(columnNode("n_1", emptyMap(), listOf(textNode("n_2", "Hi"))))
        val incoming = listOf(
            Diagnostic(Severity.Error, DiagnosticCodes.ComponentUnknown, DiagnosticLocation(), "boom"),
        )
        val result = generate(document, incoming)

        assertTrue(result.files.files.isEmpty())
        assertEquals(incoming, result.diagnostics)
    }

    @Test
    fun `a node without a spec reports no binding`() {
        val root = ResolvedNode(NodeId("n_1"), ghostType, emptyMap(), emptyList(), emptyMap(), emptySet())
        val result = generate(homeDocument(root))

        assertTrue(result.files.files.isEmpty())
        assertEquals(listOf("codegen.no_binding"), result.diagnostics.map { it.code.value })
    }

    @Test
    fun `a computed property reports unsupported`() {
        val prop = ResolvedProp(
            textKey,
            PropertyValue.Computed(Expr.Const(Value.Str("x"))),
            PropOrigin.Specified,
            null,
        )
        val root = ResolvedNode(NodeId("n_1"), textType, mapOf(textKey to prop), emptyList(), emptyMap(), emptySet())
        val result = generate(homeDocument(root))

        assertTrue(result.files.files.isEmpty())
        assertEquals(listOf("codegen.strategy_unsupported"), result.diagnostics.map { it.code.value })
    }

    @Test
    fun `a spacing reads as an arrangement call`() {
        val props = mapOf(
            spacingKey to ResolvedProp(
                spacingKey,
                PropertyValue.Const(Value.Dp(8f)),
                PropOrigin.Specified,
                null,
            ),
        )
        val result = generate(homeDocument(columnNode("n_1", props, listOf(textNode("n_2", "Hi")))))

        assertTrue(result.diagnostics.isEmpty(), "got ${result.diagnostics}")
        val screen = result.files.files.single { it.path == "screens/HomeScreen.kt" }
        assertTrue(
            screen.content.contains("verticalArrangement = Arrangement.spacedBy(8.0.dp)"),
            screen.content,
        )
        assertTrue(
            screen.content.contains("import androidx.compose.foundation.layout.Arrangement\n"),
            screen.content,
        )
    }

    @Test
    fun `modifiers chain off the modifier parameter`() {
        val entry = ResolvedModifier(
            paddingType,
            mapOf(
                PropertyKey("all") to ResolvedProp(
                    PropertyKey("all"),
                    PropertyValue.Const(Value.Dp(8f)),
                    PropOrigin.Specified,
                    null,
                ),
            ),
        )
        val root = ResolvedNode(
            NodeId("n_1"),
            columnType,
            emptyMap(),
            listOf(entry),
            mapOf(childrenSlot to listOf(textNode("n_2", "Hi"))),
            emptySet(),
        )
        val result = generate(homeDocument(root))

        assertTrue(result.diagnostics.isEmpty(), "got ${result.diagnostics}")
        val screen = result.files.files.single { it.path == "screens/HomeScreen.kt" }
        assertTrue(screen.content.contains("modifier = modifier\n"), screen.content)
        assertTrue(screen.content.contains(".padding(all = 8.0.dp)"), screen.content)
        assertTrue(
            screen.content.contains("import androidx.compose.foundation.layout.padding\n"),
            screen.content,
        )
    }

    private fun generate(
        document: ResolvedDocument,
        incoming: List<Diagnostic> = emptyList(),
    ): CodegenResult =
        KotlinGenerator(testSchema(), CodegenOptions("com.example.app")).generate(document, incoming)

    private fun homeDocument(root: ResolvedNode): ResolvedDocument {
        val pages = mapOf(PageId("p_home") to ResolvedPage(PageId("p_home"), "Home", "home", root))
        return ResolvedDocument(pages, emptyMap(), indexOf(pages), ResolvedTheme(null))
    }

    private fun indexOf(pages: Map<PageId, ResolvedPage>): Map<NodeId, ResolvedNode> {
        val index = LinkedHashMap<NodeId, ResolvedNode>()
        fun walk(node: ResolvedNode) {
            index[node.id] = node
            for (kids in node.slots.values) kids.forEach(::walk)
        }
        for (page in pages.values) walk(page.root)
        return index
    }

    private fun textNode(id: String, text: String): ResolvedNode = textAs(id, textType, text)

    private fun textAs(id: String, type: ComponentType, text: String): ResolvedNode = ResolvedNode(
        NodeId(id),
        type,
        mapOf(
            textKey to ResolvedProp(
                textKey,
                PropertyValue.Const(Value.Str(text)),
                PropOrigin.Specified,
                null,
            ),
        ),
        emptyList(),
        emptyMap(),
        emptySet(),
    )

    private fun columnNode(
        id: String,
        props: Map<PropertyKey, ResolvedProp>,
        kids: List<ResolvedNode>,
    ): ResolvedNode = ResolvedNode(
        NodeId(id),
        columnType,
        props,
        emptyList(),
        if (kids.isEmpty()) emptyMap() else mapOf(childrenSlot to kids),
        emptySet(),
    )

    private fun testSchema(): Schema<ComponentSpec, ModifierSpec, String, String, String> =
        Schema.build {
            val spacing = prop<Float>("spacing", TypeRef.Dp)
            component(
                componentSpec(columnType, 1) {
                    metadata("Column", Category.Layout)
                    property(spacing)
                    slot("children", Cardinality.Many)
                    composeCall(KotlinSymbol("androidx.compose.foundation.layout", "Column")) {
                        param(
                            "verticalArrangement",
                            from = listOf(spacing.key),
                            emit = ValueEmit.Cases(
                                listOf(
                                    EmitCase(
                                        setOf(spacing.key),
                                        "Arrangement.spacedBy({spacing})",
                                        listOf(
                                            KotlinSymbol(
                                                "androidx.compose.foundation.layout",
                                                "Arrangement",
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        )
                        slot("children", LambdaTarget.Trailing)
                    }
                },
            )
            component(textStub(textType, KotlinSymbol("androidx.compose.material3", "Text")))
            modifier(
                ModifierSpec(
                    paddingType,
                    ModifierMetadata("Padding"),
                    listOf(prop<Float>("all", TypeRef.Dp)),
                    emit = ModifierEmit(KotlinSymbol("androidx.compose.foundation.layout", "padding")),
                ),
            )
        }

    private fun columnStub(type: ComponentType): ComponentSpec =
        componentSpec(type, 1) {
            metadata("Column", Category.Layout)
            slot("children", Cardinality.Many)
            composeCall(KotlinSymbol("androidx.compose.foundation.layout", "Column")) {
                slot("children", LambdaTarget.Trailing)
            }
        }

    private fun textStub(type: ComponentType, function: KotlinSymbol): ComponentSpec {
        val text = prop<String>("text", TypeRef.Str, required = true)
        return componentSpec(type, 1) {
            metadata("Text", Category.Basic)
            property(text)
            composeCall(function) {
                param("text", from = text, positional = Positional.WhenSole)
            }
        }
    }
}
