package dev.rotalex.lutter.codegen

import dev.rotalex.lutter.analysis.diagnostic.DiagnosticCodes
import dev.rotalex.lutter.analysis.resolved.PropOrigin
import dev.rotalex.lutter.analysis.resolved.ResolvedDocument
import dev.rotalex.lutter.analysis.resolved.ResolvedNode
import dev.rotalex.lutter.analysis.resolved.ResolvedPage
import dev.rotalex.lutter.analysis.resolved.ResolvedProp
import dev.rotalex.lutter.analysis.resolved.ResolvedState
import dev.rotalex.lutter.analysis.resolved.ResolvedTheme
import dev.rotalex.lutter.model.doc.Persistence
import dev.rotalex.lutter.model.doc.StateDecl
import dev.rotalex.lutter.model.expr.BinaryOp
import dev.rotalex.lutter.model.expr.Expr
import dev.rotalex.lutter.model.expr.ExprType
import dev.rotalex.lutter.model.expr.PropertyValue
import dev.rotalex.lutter.model.expr.RefTarget
import dev.rotalex.lutter.model.expr.TypedExpr
import dev.rotalex.lutter.model.ids.ComponentDeclId
import dev.rotalex.lutter.model.ids.ComponentType
import dev.rotalex.lutter.model.ids.NodeId
import dev.rotalex.lutter.model.ids.PageId
import dev.rotalex.lutter.model.ids.PropertyKey
import dev.rotalex.lutter.model.ids.SlotName
import dev.rotalex.lutter.model.ids.StateId
import dev.rotalex.lutter.model.ids.TypeId
import dev.rotalex.lutter.model.type.TypeRef
import dev.rotalex.lutter.model.value.Value
import dev.rotalex.lutter.schema.Schema
import dev.rotalex.lutter.schema.component.Cardinality
import dev.rotalex.lutter.schema.component.Category
import dev.rotalex.lutter.schema.component.ComponentSpec
import dev.rotalex.lutter.schema.component.KotlinSymbol
import dev.rotalex.lutter.schema.component.LambdaTarget
import dev.rotalex.lutter.schema.component.Positional
import dev.rotalex.lutter.schema.component.component
import dev.rotalex.lutter.schema.component.componentSpec
import dev.rotalex.lutter.schema.component.prop
import dev.rotalex.lutter.schema.function.FunctionSpec
import dev.rotalex.lutter.schema.modifier.ModifierSpec
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * PLAN §12.1's four kinds, asserted as the files a document turns into.
 *
 * Each golden is the whole file rather than a fragment, because the two things this unit can get
 * wrong are both invisible to a substring: an import the class needs and does not have, and a
 * member read that resolved through the screen's `state` instead of the class's own `this`.
 */
class StateEmitterTest {

    private val columnType: ComponentType = ComponentType("test.Column")
    private val textType: ComponentType = ComponentType("test.Text")
    private val textKey: PropertyKey = PropertyKey("text")
    private val childrenSlot: SlotName = SlotName("children")
    private val home: PageId = PageId("p_home")
    private val card: ComponentDeclId = ComponentDeclId("ProfileCard")

    private val count: StateId = StateId("s_count")
    private val label: StateId = StateId("s_label")
    private val doubled: StateId = StateId("s_doubled")
    private val theme: StateId = StateId("s_theme")

    @Test
    fun `a page's declarations become its state class and the parameter that carries it`() {
        val screen = screenOf(pageDocument(heldPageState()))

        assertEquals(
            """
            // Generated by Forge. Do not edit.
            package com.example.app.screens

            ${"import"} androidx.compose.foundation.layout.Column
            ${"import"} androidx.compose.material3.Text
            ${"import"} androidx.compose.runtime.Composable
            ${"import"} androidx.compose.runtime.Stable
            ${"import"} androidx.compose.runtime.getValue
            ${"import"} androidx.compose.runtime.mutableStateOf
            ${"import"} androidx.compose.runtime.remember
            ${"import"} androidx.compose.runtime.setValue
            ${"import"} androidx.compose.ui.Modifier

            @Stable
            public class HomeScreenState {
                public var count: Int by mutableStateOf(0)

                public var label: String by mutableStateOf("Clicks")

                public val doubled: Int
                    get() = count + 1
            }

            @Composable
            public fun rememberHomeScreenState(): HomeScreenState {
                val state: HomeScreenState = remember {
                    HomeScreenState()
                }
                return(state)
            }

            @Composable
            public fun HomeScreen(modifier: Modifier = Modifier, state: HomeScreenState = rememberHomeScreenState()) {
                Column(
                    modifier = modifier,
                ) {
                    Text("Clicks")
                    Text("Total")
                }
            }

            """.trimIndent(),
            screen,
        )
    }

    @Test
    fun `a derived declaration is a getter over its sibling, not over the screen's parameter`() {
        val screen = screenOf(pageDocument(heldPageState()))

        // The whole point of the class: `state.count` compiles here and reads nothing, because
        // the parameter is not in scope inside the class body.
        assertTrue(screen.contains("get() = count + 1"), screen)
        assertTrue(!screen.contains("state.count"), screen)
    }

    @Test
    fun `a page that declares nothing emits the screen it emitted before state existed`() {
        // The other five conformance fixtures depend on this: adding a state class and a
        // parameter to a document that asked for neither would change every golden for nothing.
        val screen = screenOf(pageDocument(emptyList()))

        assertEquals(
            """
            // Generated by Forge. Do not edit.
            package com.example.app.screens

            ${"import"} androidx.compose.foundation.layout.Column
            ${"import"} androidx.compose.material3.Text
            ${"import"} androidx.compose.runtime.Composable
            ${"import"} androidx.compose.ui.Modifier

            @Composable
            public fun HomeScreen(modifier: Modifier = Modifier) {
                Column(
                    modifier = modifier,
                ) {
                    Text("Clicks")
                    Text("Total")
                }
            }

            """.trimIndent(),
            screen,
        )
    }

    @Test
    fun `app state becomes its own file and is provided where AppRoot builds the tree`() {
        val document = pageDocument(emptyList(), appState = listOf(heldTheme()))
        val files = generate(document)

        assertTrue(files.diagnostics.isEmpty(), "got ${files.diagnostics}")
        assertEquals(
            """
            // Generated by Forge. Do not edit.
            package com.example.app.state

            ${"import"} androidx.compose.runtime.ProvidableCompositionLocal
            ${"import"} androidx.compose.runtime.getValue
            ${"import"} androidx.compose.runtime.mutableStateOf
            ${"import"} androidx.compose.runtime.setValue
            ${"import"} androidx.compose.runtime.staticCompositionLocalOf

            public class AppState {
                public var theme: String by mutableStateOf("light")
            }

            public val LocalAppState: ProvidableCompositionLocal<AppState> = staticCompositionLocalOf<AppState> {
                AppState()
            }

            """.trimIndent(),
            content(files, "state/AppState.kt"),
        )
        assertEquals(
            """
            // Generated by Forge. Do not edit.
            package com.example.app

            ${"import"} androidx.compose.runtime.Composable
            ${"import"} androidx.compose.runtime.CompositionLocalProvider
            ${"import"} androidx.compose.runtime.remember
            ${"import"} androidx.compose.ui.Modifier
            ${"import"} com.example.app.screens.HomeScreen
            ${"import"} com.example.app.state.AppState
            ${"import"} com.example.app.state.LocalAppState

            @Composable
            public fun AppRoot(navigator: AppNavigator, modifier: Modifier = Modifier) {
                val state: AppState = remember {
                    AppState()
                }
                CompositionLocalProvider(
                    LocalAppState.provides(state),
                ) {
                    when (navigator.current) {
                        Route.Home -> {
                            HomeScreen(
                                modifier = modifier,
                            )
                        }
                    }
                }
            }

            """.trimIndent(),
            content(files, "App.kt"),
        )
    }

    @Test
    fun `a document with no app state emits no app-state file and an unwrapped AppRoot`() {
        val files = generate(pageDocument(emptyList()))

        assertTrue(files.diagnostics.isEmpty(), "got ${files.diagnostics}")
        assertEquals(
            listOf("App.kt", "AppHost.kt", "Navigation.kt", "screens/HomeScreen.kt"),
            files.files.files.map { it.path },
        )
        assertTrue(!content(files, "App.kt").contains("CompositionLocalProvider"), content(files, "App.kt"))
    }

    @Test
    fun `component state becomes locals at the top of the composable`() {
        val files = generate(pageDocument(emptyList(), componentHeld = componentState()))

        assertTrue(files.diagnostics.isEmpty(), "got ${files.diagnostics}")
        assertEquals(
            """
            // Generated by Forge. Do not edit.
            package com.example.app.components

            ${"import"} androidx.compose.foundation.layout.Column
            ${"import"} androidx.compose.material3.Text
            ${"import"} androidx.compose.runtime.Composable
            ${"import"} androidx.compose.runtime.getValue
            ${"import"} androidx.compose.runtime.mutableStateOf
            ${"import"} androidx.compose.runtime.remember
            ${"import"} androidx.compose.runtime.setValue
            ${"import"} androidx.compose.ui.Modifier

            @Composable
            public fun ProfileCard(modifier: Modifier = Modifier) {
                var count: Int by remember {
                    mutableStateOf(0)
                }
                var label: String by remember {
                    mutableStateOf("Hi")
                }
                Column(
                    modifier = modifier,
                ) {
                    Text("Hi")
                }
            }

            """.trimIndent(),
            content(files, "components/ProfileCard.kt"),
        )
    }

    @Test
    fun `a read resolves through the scope the declaration was written in`() {
        val document = pageDocument(heldPageState(), appState = listOf(heldTheme()))
        val options: CodegenOptions = CodegenOptions("com.example.app")
        val emitter: StateEmitter = StateEmitter(document, options, schema().functions)

        // §12.1's page and app rows, and the component row's bare local. The identifier is the
        // document's `name`, not the id: §6.2 makes a rename change one and not the other.
        assertEquals(KtExpr.Member(KtExpr.Name("state"), "count"), emitter.readInScreen(count))
        val localAppState: KotlinSymbol = KotlinSymbol("com.example.app.state", "LocalAppState")
        assertEquals(
            KtExpr.Member(KtExpr.Member(KtExpr.Ref(KtSymbolRef(localAppState)), "current"), "theme"),
            emitter.readInScreen(theme),
        )
        assertEquals(KtExpr.Member(KtExpr.Name("state"), "doubled"), emitter.readInScreen(doubled))
        assertNull(emitter.readInScreen(StateId("s_absent")))
    }

    @Test
    fun `a persistence no strategy emits is refused rather than silently downgraded`() {
        val saveable = StateDecl(count, "count", TypeRef.Int32, Value.Int32(0), null, Persistence.Saveable)
        val result = generate(pageDocument(listOf(held(saveable))))

        assertTrue(result.files.files.isEmpty())
        assertEquals(listOf("codegen.strategy_unsupported"), result.diagnostics.map { it.code.value })
        assertEquals(
            "State 'count' asks to be Saveable, which no strategy emits yet",
            result.diagnostics.single().message,
        )
    }

    @Test
    fun `a type with no Kotlin spelling is refused by name`() {
        // §16.7: the type arrives from the user's document, so it is a finding and not a throw.
        val unspellable = StateDecl(count, "count", TypeRef.Enum(TypeId("testAlignment")), Value.Int32(0))
        val result = generate(pageDocument(listOf(held(unspellable))))

        assertTrue(result.files.files.isEmpty())
        assertEquals(listOf(DiagnosticCodes.CodegenNoTypeSpelling), result.diagnostics.map { it.code })
        assertEquals(
            "State 'count' is typed 'enum', which has no Kotlin spelling: " +
                "no Kotlin type name is carried by it or its spec",
            result.diagnostics.single().message,
        )
    }

    @Test
    fun `a derived declaration in a component is refused because a getter is a member`() {
        val derivedComponent = ResolvedState(
            StateDecl(doubled, "doubled", TypeRef.Int32, null, Expr.Const(Value.Int32(1))),
            typed(Expr.Const(Value.Int32(1))),
        )
        val result = generate(pageDocument(emptyList(), componentHeld = listOf(derivedComponent)))

        assertTrue(result.files.files.isEmpty())
        assertEquals(listOf("codegen.strategy_unsupported"), result.diagnostics.map { it.code.value })
        assertEquals(
            "State 'doubled' is derived, and §12.1's derived shape is a class member",
            result.diagnostics.single().message,
        )
    }

    // A held `Int` named `count`, a held `String` named `label`, and `count + 1` named
    // `doubled`: `StateResolutionTest` already proves this trio resolves and type-checks, so the
    // document here is the same fact expressed on the wire.
    private fun heldPageState(): List<ResolvedState> = listOf(
        held(StateDecl(count, "count", TypeRef.Int32, Value.Int32(0))),
        held(StateDecl(label, "label", TypeRef.Str, Value.Str("Clicks"))),
        ResolvedState(
            StateDecl(
                doubled,
                "doubled",
                TypeRef.Int32,
                null,
                Expr.Binary(
                    BinaryOp.Add,
                    Expr.Ref(RefTarget.State(count)),
                    Expr.Const(Value.Int32(1)),
                ),
            ),
            typed(
                Expr.Binary(
                    BinaryOp.Add,
                    Expr.Ref(RefTarget.State(count)),
                    Expr.Const(Value.Int32(1)),
                ),
            ),
        ),
    )

    private fun heldTheme(): ResolvedState = held(StateDecl(theme, "theme", TypeRef.Str, Value.Str("light")))

    private fun componentState(): List<ResolvedState> = listOf(
        held(StateDecl(count, "count", TypeRef.Int32, Value.Int32(0))),
        held(StateDecl(label, "label", TypeRef.Str, Value.Str("Hi"))),
    )

    private fun held(decl: StateDecl): ResolvedState = ResolvedState(decl, null)

    private fun typed(expr: Expr): TypedExpr = TypedExpr(expr, ExprType.Of(TypeRef.Int32), emptySet())

    private fun pageDocument(
        pageState: List<ResolvedState>,
        appState: List<ResolvedState> = emptyList(),
        componentHeld: List<ResolvedState> = emptyList(),
    ): ResolvedDocument {
        val pages = mapOf(home to ResolvedPage(home, "Home", "home", column("n_root", "Clicks", "Total"), pageState))
        val components = if (componentHeld.isEmpty()) {
            emptyMap()
        } else {
            mapOf(card to column("n_card_root", "Hi"))
        }
        val nodeIndex = LinkedHashMap<NodeId, ResolvedNode>()
        nodeIndex[NodeId("n_root")] = column("n_root", "Clicks", "Total")
        nodeIndex[NodeId("n_card_root")] = column("n_card_root", "Hi")
        return ResolvedDocument(
            pages,
            components,
            nodeIndex,
            ResolvedTheme(null),
            appState,
            if (componentHeld.isEmpty()) emptyMap() else mapOf(card to componentHeld),
        )
    }

    private fun screenOf(document: ResolvedDocument): String {
        val files = generate(document)
        assertTrue(files.diagnostics.isEmpty(), "got ${files.diagnostics}")
        return content(files, "screens/HomeScreen.kt")
    }

    private fun content(files: CodegenResult, path: String): String =
        files.files.files.firstOrNull { it.path == path }?.content
            ?: error("no '$path' in ${files.files.files.map { it.path }}")

    private fun generate(document: ResolvedDocument): CodegenResult =
        KotlinGenerator(schema(), CodegenOptions("com.example.app")).generate(document)

    private fun column(id: String, vararg texts: String): ResolvedNode = ResolvedNode(
        NodeId(id),
        columnType,
        emptyMap(),
        emptyList(),
        if (texts.isEmpty()) {
            emptyMap()
        } else {
            mapOf(childrenSlot to texts.mapIndexed { index, text -> textNode(id + "_" + index, text) })
        },
        emptySet(),
    )

    private fun textNode(id: String, text: String): ResolvedNode = ResolvedNode(
        NodeId(id),
        textType,
        mapOf(
            textKey to ResolvedProp(
                textKey,
                PropertyValue.Const(Value.Str(text)),
                PropOrigin.Specified,
                null,
            ),
        ),
        emptyList(),
        emptyMap(),
        emptySet(),
    )

    private fun schema(): Schema<ComponentSpec, ModifierSpec, String, FunctionSpec, String> {
        val text = prop<String>("text", TypeRef.Str, required = true)
        return Schema.build {
            component(
                componentSpec(columnType, 1) {
                    metadata("Column", Category.Layout)
                    slot("children", Cardinality.Many)
                    composeCall(KotlinSymbol("androidx.compose.foundation.layout", "Column")) {
                        slot("children", LambdaTarget.Trailing)
                    }
                },
            )
            component(
                componentSpec(textType, 1) {
                    metadata("Text", Category.Basic)
                    property(text)
                    composeCall(KotlinSymbol("androidx.compose.material3", "Text")) {
                        param("text", from = text, positional = Positional.WhenSole)
                    }
                },
            )
        }
    }
}
