import javax.inject.Inject
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.Classpath
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations

plugins {
    id("forge.kmp.compose")
}

dependencies {
    commonMainApi(project(":engine:model"))
    commonMainApi(project(":engine:schema"))
    commonMainApi(project(":engine:serialization"))
    commonMainApi(project(":engine:interpreter"))
    commonMainApi(project(":engine:analysis"))
    commonMainApi(project(":engine:editing"))
    commonMainApi(project(":engine:codegen"))
    commonMainApi(project(":engine:runtime"))
    commonMainApi(project(":engine:builtins"))
    commonMainApi(project(":engine:builtins-compose"))
    // Generated screens call Column/Text directly, so the module compiling them needs more
    // than the compiler plugin's runtime: the same three artifacts builtins-compose uses.
    commonMainImplementation(rootLibs.jetbrains.compose.ui)
    commonMainImplementation(rootLibs.jetbrains.compose.foundation)
    commonMainImplementation(rootLibs.jetbrains.compose.material3)
    // Desktop-only UI test runner; commonTest stays pure so Android host tests keep running.
    desktopTestImplementation(compose.desktop.uiTestJUnit4)
}

// Build-time edge to :tools:cli, not a code dependency: this configuration is outside the
// module-graph check's list on purpose, the same way a buildscript classpath is.
val cliRuntime by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

dependencies {
    add(cliRuntime.name, project(":tools:cli"))
}

// PLAN §28.4's fixture task: runs the CLI over fixtures/*.json, then emits the document
// constants the tests decode plus the screen registry the UI test renders.
abstract class GenerateFixtures : DefaultTask() {
    @get:InputDirectory
    abstract val fixtures: DirectoryProperty

    @get:OutputDirectory
    abstract val generated: DirectoryProperty

    @get:Classpath
    abstract val cliClasspath: ConfigurableFileCollection

    @get:Inject
    abstract val exec: ExecOperations

    @TaskAction
    fun run() {
        val out = generated.get().asFile
        out.mkdirs()
        val screens = mutableMapOf<String, String>()
        val texts = mutableMapOf<String, String>()
        val files = fixtures.get().asFile.listFiles { file -> file.extension == "json" }
            ?.sortedBy { it.name } ?: emptyList()
        for (file in files) {
            val id = file.nameWithoutExtension
            val pkg = "dev.rotalex.lutter.generated." + id.replace(Regex("[^A-Za-z0-9_]"), "_")
            exec.javaexec {
                classpath = cliClasspath
                mainClass.set("dev.rotalex.lutter.cli.MainKt")
                args("generate", file.absolutePath, "--out", File(out, id).absolutePath, "--package", pkg)
            }
            val text = file.readText()
            require(!text.contains("\"\"\"")) { "Fixture '$id' holds a triple quote, which raw strings cannot carry" }
            texts[id] = text.replace("$", "${'$'}")
            screens[id] = firstScreen(pkg, text)
        }
        File(out, "FixtureDocuments.kt").writeText(documentsFile(texts))
        File(out, "GeneratedFixtures.kt").writeText(registryFile(screens))
    }

    // The screen AppRoot hosts: first page by id, the same rule the generator uses.
    private fun firstScreen(pkg: String, text: String): String {
        val root = groovy.json.JsonSlurper().parseText(text) as Map<*, *>
        val pages = (root["payload"] as Map<*, *>)["pages"] as Map<*, *>
        val first = pages.entries.sortedBy { it.key as String }.first().value as Map<*, *>
        return "$pkg.screens." + (first["name"] as String) + "Screen"
    }

    private fun documentsFile(texts: Map<String, String>): String = buildString {
        appendLine("// Generated by generateFixtures. Do not edit.")
        appendLine("package dev.rotalex.lutter.generated.compile")
        appendLine()
        appendLine("public object FixtureDocuments {")
        appendLine("    private val byId: Map<String, String> = mapOf(")
        for ((id, text) in texts) appendLine("        \"$id\" to \"\"\"$text\"\"\",")
        appendLine("    )")
        appendLine()
        appendLine("    public val ids: List<String> = byId.keys.sorted()")
        appendLine()
        appendLine("    public fun json(id: String): String =")
        appendLine("        byId[id] ?: throw IllegalArgumentException(\"No fixture '\$id'\")")
        appendLine("}")
    }

    private fun registryFile(screens: Map<String, String>): String = buildString {
        appendLine("// Generated by generateFixtures. Do not edit.")
        appendLine("package dev.rotalex.lutter.generated.compile")
        appendLine()
        appendLine("import androidx.compose.runtime.Composable")
        appendLine("import androidx.compose.ui.Modifier")
        appendLine()
        appendLine("public object GeneratedFixtures {")
        appendLine("    public val all: Map<String, @Composable (Modifier) -> Unit> = mapOf(")
        for ((id, screen) in screens) appendLine("        \"$id\" to { modifier -> $screen(modifier) },")
        appendLine("    )")
        appendLine("}")
    }
}

val generateFixtures by tasks.register<GenerateFixtures>("generateFixtures") {
    fixtures.set(layout.projectDirectory.dir("fixtures"))
    generated.set(layout.buildDirectory.dir("generated/forge"))
    cliClasspath.from(cliRuntime)
}

kotlin {
    // Passing the task wires both the directory and the dependency: compilation waits for it.
    sourceSets.named("commonMain") { kotlin.srcDir(generateFixtures) }
}
